# Profil Kafka : activer la messagerie (nécessite un broker Kafka sur localhost:9092)
app.kafka.enabled=true
# Ne pas exclure l'auto-configuration Kafka
spring.autoconfigure.exclude=

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
# Advertise 127.0.0.1 so gateway and other services on same host can reach this service
eureka.instance.ip-address=127.0.0.1
eureka.instance.hostname=localhost
