version: "3.8"

services:
  digital-banking-monolith:
    build: .
    container_name: digital-banking-monolith
    ports:
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    restart: unless-stopped


