app.kafka.enabled=true
spring.autoconfigure.exclude=

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
# Advertise 127.0.0.1 so other services on same host (e.g. transaction-service) can reach this service via Feign
eureka.instance.ip-address=127.0.0.1
eureka.instance.hostname=localhost
